baseURL: https://mehdy.me/
title: Mehdi Khoshnoodi

defaultContentLanguageInSubdir: true
defaultContentLanguage: en
languageCode: en
languageName: English

theme: PaperMod

paginate: 10

googleAnalytics: G-BK5V8GNT5V

enableRobotsTXT: true

disqusShortname: mehdy

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS

permalinks:
  posts: /posts/:year/:month/:slug/
  pages: /:slug/

taxonomies:
  tags: tags
