main:
  - weight: 1
    identifier: posts
    name: نوشته‌ها
    url: /
  - weight: 3
    identifier: about
    name: دربارهٔ من
    url: /دربارهٔ-من/
  - weight: 4
    identifier: tags
    name: تگ‌ها
    url: /tags/
  - weight: 4
    identifier: archives
    name: آرشیو
    url: /archives/
